//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TISS_JetLag.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TISS_JetLagSolutionsEntities : DbContext
    {
        public TISS_JetLagSolutionsEntities()
            : base("name=TISS_JetLagSolutionsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cause> Cause { get; set; }
        public virtual DbSet<JetLagAdjustment> JetLagAdjustment { get; set; }
        public virtual DbSet<Strategy> Strategy { get; set; }
        public virtual DbSet<SunlightAdvice> SunlightAdvice { get; set; }
        public virtual DbSet<Symptom> Symptom { get; set; }
        public virtual DbSet<TopicSymptom> TopicSymptom { get; set; }
        public virtual DbSet<TravelFatigueJetLagTopic> TravelFatigueJetLagTopic { get; set; }
        public virtual DbSet<CountryTimeZone> CountryTimeZone { get; set; }
        public virtual DbSet<AirportInfo> AirportInfo { get; set; }
    }
}
