//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TISS_JetLag.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopicSymptom
    {
        public int TopicSymptomID { get; set; }
        public int TopicID { get; set; }
        public int SymptomID { get; set; }
    
        public virtual Symptom Symptom { get; set; }
        public virtual TravelFatigueJetLagTopic TravelFatigueJetLagTopic { get; set; }
    }
}
